AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for GitHub Actions OIDC Authentication

Parameters:
  GitHubOrg:
    Type: String
    Description: "GitHub Organization or Username (例: my-org または your-username)"
  GitHubRepo:
    Type: String
    Description: "GitHub Repository name (例: fastapi-lambda-api)"
  RoleName:
    Type: String
    Default: GitHubActionsOIDCRole

Resources:
  GitHubActionsOIDCRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/main
      Policies:
        - PolicyName: GitHubActionsAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:PutImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:BatchGetImage
                  - ecr:CreateRepository
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:GetTemplateSummary
                Resource: "*"
              - Effect: Allow
                Action:
                  - lambda:UpdateFunctionCode
                  - lambda:GetFunction
                  - lambda:CreateFunction
                  - lambda:AddPermission
                Resource: "*"
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: "*"

Outputs:
  RoleArn:
    Description: ARN of the OIDC Role to use in GitHub Actions
    Value: !GetAtt GitHubActionsOIDCRole.Arn
